[package]
name = "yos_kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = { workspace = true }
linked_list_allocator = { workspace = true }
spin = { workspace = true }
bootloader = { workspace = true }
volatile = { workspace = true }
x86_64 = { workspace = true }
